import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "./providers";
import { Navbar } from "@/widgets/navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const initialLocale = cookieStore.get("locale")?.value === "en" ? "en" : "ar";
  const initialTheme = cookieStore.get("theme")?.value === "dark" ? "dark" : "light";

  return (
    <html
      lang={initialLocale}
      dir={initialLocale === "ar" ? "rtl" : "ltr"}
      suppressHydrationWarning
    >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="global-ambient" aria-hidden>
          {[...Array(20)].map((_, i) => (
            <span 
              key={i} 
              className="meteor" 
              style={{ 
                '--meteor-delay': `${i * 1.5}s`,
                '--meteor-duration': `${2.2 + Math.random() * 1.2}s`,
                '--meteor-start-left': `${Math.random() * 90 + 5}%`,
                '--meteor-start-top': `${Math.random() * 50}%`,
              } as React.CSSProperties} 
            >
              <style>{`
                .meteor:nth-child(${i + 1})::before {
                  animation: meteor-trail var(--meteor-duration, 2.5s) cubic-bezier(0.15, 0.82, 0.25, 1) infinite;
                  animation-delay: var(--meteor-delay);
                }
              `}</style>
            </span>
          ))}
        </div>
        <div className="relative z-10">
          <Providers initialLocale={initialLocale} initialTheme={initialTheme}>
            <Navbar />
            <main>{children}</main>
          </Providers>
        </div>
      </body>
    </html>
  );
}
